export const FETCH_CURRENT_USER = 'Home/FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'Home/FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_ERROR = 'Home/FETCH_CURRENT_USER_ERROR';
